### ISSUE TITLE
When I try to open the project I got an error window. 

### ISSUE THREAD

**Issue by o986o** [keijiro/Akvfx#23]
When I try to open the project I got an error window. 
I open the project in Unity 2019. 3. 14f1.

when I open the project at first I got this error window. 
![image](https://user-images.githubusercontent.com/33400694/98220778-2ae0e480-1f92-11eb-92a0-24b0722f3f67.png)

when I click continuew button, I can see the below errors on the console. 
![image](https://user-images.githubusercontent.com/33400694/98221041-84491380-1f92-11eb-89aa-de09639ada27.png)

I wonder how can I solve these problems.

**Comment by keijiro** [comment]
This error was caused by the UnityNuGet registry. The issue has been already fixed. Clear the Package Manager cache directory and retry opening the project.

**Comment by o986o** [comment]
> This error was caused by the UnityNuGet registry. The issue has been already fixed. Clear the Package Manager cache directory and retry opening the project.

Thanks for your fast reply. 
I feel I do not know where is the package manager cache directory. 
Anyway, I try to delete something that I guess similar to cache something. 
But I still have an error message window. 

The symptom is this. 

![image](https://user-images.githubusercontent.com/33400694/98349207-0e5dae80-205d-11eb-8f6a-03cdd52dbf03.png)
when I clicked continue button. 
![image](https://user-images.githubusercontent.com/33400694/98349554-7a401700-205d-11eb-8ba4-28559ea96e7b.png)


I deleted my package manager cache and also I deleted manifest.json.
![image](https://user-images.githubusercontent.com/33400694/98349845-d73bcd00-205d-11eb-8a1d-caed591069e0.png)

![image](https://user-images.githubusercontent.com/33400694/98349299-2a615000-205d-11eb-8932-2e44498b48c1.png)
![image](https://user-images.githubusercontent.com/33400694/98349366-3ea54d00-205d-11eb-89d9-dd609ebc031f.png)

![image](https://user-images.githubusercontent.com/33400694/98349321-2e8d6d80-205d-11eb-92ba-bc9242809133.png)

**Comment by keijiro** [comment]
You shouldn't delete the files in the project directory, like manifest.json.

You only have to clear the cache under `user/AppData`

**Comment by o986o** [comment]
> You shouldn't delete the files in the project directory, like manifest.json.
> 
> You only have to clear the cache under `user/AppData`

Thanks a lot, Keijiro san. I success to open the project. 

If someone has the same problem as me, just delete the package cache as under image.
The directory is this.
> C:\Users\user\AppData\Local\Unity\cache
I deleted everything in the Cache folder.
 
I hope this helps you. 

![image](https://user-images.githubusercontent.com/33400694/98355693-dc9d1580-2065-11eb-804f-1a30efa06d2c.png)
